'use client';

import { useState } from 'react';
import { mockTemplates } from '@/lib/data';
import { FileText, User, FileCheck } from 'lucide-react';

interface ContractFormProps {
  onSubmit: (data: any) => void;
}

export default function ContractForm({ onSubmit }: ContractFormProps) {
  const [formData, setFormData] = useState({
    title: '',
    client: '',
    description: '',
    template: '',
  });

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    
    // Simular automatización de documentos
    const selectedTemplate = mockTemplates.find((t) => t.id === formData.template);
    let autoGeneratedContent = `Contrato generado automáticamente para ${formData.client}\n\n`;
    
    if (selectedTemplate) {
      autoGeneratedContent += `Plantilla utilizada: ${selectedTemplate.name}\n`;
      autoGeneratedContent += `Cláusulas incluidas: ${selectedTemplate.clauses.length}\n\n`;
    }
    
    autoGeneratedContent += `Título: ${formData.title}\n`;
    if (formData.description) {
      autoGeneratedContent += `Descripción: ${formData.description}\n`;
    }
    
    // Simular delay de generación
    setTimeout(() => {
      onSubmit({
        title: formData.title,
        client: formData.client,
        description: formData.description,
        templateId: formData.template || undefined,
      });
      setFormData({
        title: '',
        client: '',
        description: '',
        template: '',
      });
    }, 500);
  };

  return (
    <div className="max-w-2xl mx-auto">
      <div className="card">
        <h3 className="text-xl font-semibold text-primary-dark mb-6">
          Información del Contrato
        </h3>

        <form onSubmit={handleSubmit} className="space-y-6">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              <FileText className="w-4 h-4 inline mr-1" />
              Título del Contrato *
            </label>
            <input
              type="text"
              required
              value={formData.title}
              onChange={(e) => setFormData({ ...formData, title: e.target.value })}
              className="input-field"
              placeholder="Ej: Contrato de Servicios Tecnológicos"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              <User className="w-4 h-4 inline mr-1" />
              Cliente *
            </label>
            <input
              type="text"
              required
              value={formData.client}
              onChange={(e) => setFormData({ ...formData, client: e.target.value })}
              className="input-field"
              placeholder="Ej: Empresa ABC S.A."
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              <FileCheck className="w-4 h-4 inline mr-1" />
              Plantilla (opcional)
            </label>
            <select
              value={formData.template}
              onChange={(e) => setFormData({ ...formData, template: e.target.value })}
              className="input-field"
            >
              <option value="">Seleccionar plantilla...</option>
              {mockTemplates.map((template) => (
                <option key={template.id} value={template.id}>
                  {template.name}
                </option>
              ))}
            </select>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Descripción
            </label>
            <textarea
              value={formData.description}
              onChange={(e) => setFormData({ ...formData, description: e.target.value })}
              className="input-field"
              rows={4}
              placeholder="Descripción detallada del contrato..."
            />
          </div>

          <div className="bg-blue-50 border-l-4 border-blue-500 p-4 rounded-lg mb-4">
            <p className="text-sm text-gray-700">
              <strong>Automatización:</strong> Al seleccionar una plantilla, el sistema generará automáticamente 
              el contrato con las cláusulas correspondientes y podrás revisarlo antes de guardarlo.
            </p>
          </div>

          <div className="flex gap-4 pt-4">
            <button type="submit" className="btn-accent flex-1 flex items-center justify-center gap-2">
              <FileCheck className="w-5 h-5" />
              Generar Contrato Automáticamente
            </button>
            <button
              type="button"
              onClick={() => setFormData({
                title: '',
                client: '',
                description: '',
                template: '',
              })}
              className="btn-secondary"
            >
              Limpiar
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}

